version: "3"
services:
  api:
    image: "docker-node-mongo-todo-app"
    build:
      context: ./
      dockerfile: Dockerfile.server
    container_name: server
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongo
    ports:
      - "9090:9090"
    depends_on:
      - mongo

  ui:
    build:
      context: ./
      dockerfile: Dockerfile.ui
    container_name: Angular
    ports:
      - 4200:80
    links:
      - api

  mongo:
    image: mongo:5
    ports:
      - "9091:27017"
    volumes:
      - database:/data/db
    networks:
      - app7
volumes:
  database:
networks:
  app7:
